language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then travis_retry pip install unittest2; fi
before_script:
  - echo 'Etc/UTC' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - cat /etc/timezone
# command to run tests
script:
  - python ./test_demo.py -v
  - python -m unittest discover -v
